### ISSUE TITLE
Version 0.4.0: Could not load file or assembly 'Microsoft.Xrm.Sdk, Version=7.0.0.0

### ISSUE THREAD

**Issue by henrikhannemose** [delegateas/XrmMockup#17]
With version 0.3.5 my XrmMockup worked just fine.

After updating to 0.4.0 I get the following error:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Xrm.Sdk, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER)) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DG.Tools.XrmMockup.Metadata.AssemblyGetter.GetProjectPath() in C:\git\XrmMockup\src\MetadataShared\AssemblyGetter.cs:line 65
   at DG.Tools.XrmMockup.Metadata.AssemblyGetter.GetAssemblyFromName(String Name) in C:\git\XrmMockup\src\MetadataShared\AssemblyGetter.cs:line 14
   at DG.Tools.XrmMockup.Metadata.Program.ResolveXrmAssemblies(Object sender, ResolveEventArgs args) in C:\git\XrmMockup\src\MetadataShared\Program.cs:line 28
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   --- End of inner exception stack trace ---
   at DG.Tools.XrmMockup.Metadata.Program.Main(String[] args)
```

**Comment by henrikhannemose** [comment]
Fixed in https://github.com/delegateas/XrmMockup/commit/1e47b32fdae7f0dedd3af296f91a3ca2072b34fc. To be released as part of 0.4.1 (no nuget package generated yet)
