### ISSUE TITLE
Metadata Generator Exception: An item with the same key has already been added

### ISSUE THREAD

**Issue by maerger** [delegateas/XrmMockup#193]
**Describe the bug**
I tried to recreate my metadata. No change of version and/or configuration. I get the following error message:

Unhandled Exception: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at DG.Tools.XrmMockup.Metadata.DataHelper.GetSecurityRoles(Guid rootBUId)
   at DG.Tools.XrmMockup.Metadata.Program.GenerateMetadata()
   at DG.Tools.XrmMockup.Metadata.Program.Main(String[] args)

**To Reproduce**
Think this is related to my environment

**Expected behavior**
Creation of updated metadata

**Environment**
- CRM/D365/CDS version: [e.g. 9.2]
- Tool version: 1.8.0
- Dynamics Marketing Solution only installed

**Additional context**Add any other context about the problem here. Error messages og solution files.
My config:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="url" value="https://dev1-hsluzern.crm4.dynamics.com" />
    <add key="method" value="ClientSecret" />
    <add key="mfaAppId" value="{e42171f6-a399-4595-9cbe-7054d32c82bf}" />
    <add key="mfaClientSecret" value="ytN69-Py-PbsBLVIfv4isdd.rl.5L9LLFE" />
    <add key="solutions" value="HsluD365, HsluD365Plugins" />
    <add key="entities" value="account, activitypointer, activityparty, hslu_configuration, contact, email, hslu_logs, hslu_person, team, list, listmember, hslu_contract, hslu_industry, hslu_keyaccountmanager, hslu_projectpartner, hslu_personalnote" />
    <add key="fetchFromAssemblies" value="false" />
  </appSettings>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.2" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

**Comment by maerger** [comment]
Update to 1.8.1 solved the issue - sorry!
