### ISSUE TITLE
Inactive incidents can be modified through Mockup.

### ISSUE THREAD

**Issue by lisby** [delegateas/XrmMockup#78]
The following plugin trace is hit if you modify an inactive incident through the SDK:
[Microsoft.Dynamics.Service.Plugins: Microsoft.Dynamics.Service.Plugins.PreOperationIncidentUpdate]
 	[b986a294-28b3-e611-80f0-00155dc13602: PreOperation of Incident Update]
 	Entered Microsoft.Dynamics.Service.Plugins.PreOperationIncidentUpdate.Execute(), Correlation Id: 1e812ac8-f31d-4345-9ab6-6a62323524f4, Initiating User: 6e160d0b-a13a-486a-bdc8-c5a2f5e8b305
 	Exception: Microsoft.Dynamics.Solution.Common.CrmException: This case has already been resolved. Close and reopen the case record to see the updates. (Fault Detail is equal to Exception details: 
 	ErrorCode: 0x800404CF
 	Message: This case has already been resolved. Close and reopen the case record to see the updates.
 	StackTrace: 
     at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
     at System.Environment.get_StackTrace()
     at Microsoft.Dynamics.Solution.Common.CrmException.BuildOrganizationServiceFault(Exception innerException, Int32 errorCode, String message)
     at Microsoft.Dynamics.Solution.Common.CrmException..ctor(String message, Exception innerException, Int32 errorCode, Boolean isFlowControlException, Boolean enableTrace)
     at Microsoft.Dynamics.Solution.Common.CrmException..ctor(String message, Exception innerException, Int32 errorCode, Boolean isFlowControlException)
     at Microsoft.Dynamics.Solution.Common.CrmException..ctor(String message, Int32 errorCode)
     at Microsoft.Crm.Service.ObjectModel.IncidentService.PreValidateForUpdate(Case incident, ISecurityService securityService)
     at Microsoft.Dynamics.Service.Plugins.PreOperationIn...)., Correlation Id: 1e812ac8-f31d-4345-9ab6-6a62323524f4, Initiating User: 6e160d0b-a13a-486a-bdc8-c5a2f5e8b305
 	Exiting Microsoft.Dynamics.Service.Plugins.PreOperationIncidentUpdate.Execute(), Correlation Id: 1e812ac8-f31d-4345-9ab6-6a62323524f4, Initiating User: 6e160d0b-a13a-486a-bdc8-c5a2f5e8b305

Doing so in mockup is allowed.

The following plugin is sufficient to reproduce CRM behavior:
```
public class IncidentBlockModifyingInactive : Plugin
    {
        public IncidentBlockModifyingInactive() : base(typeof(IncidentBlockModifyingInactive))
        {
            RegisterPluginStep<Incident>(EventOperation.Update, ExecutionStage.PreValidation, VerifyActive);
        }

        private void VerifyActive(LocalPluginContext obj)
        {
            var i = Incident.Retrieve(obj.OrganizationAdminService, obj.PluginExecutionContext.PrimaryEntityId, x => x.StateCode);
            if (i.StateCode != IncidentState.Active) {
                throw new Exception("Cannot modify inactive incident!");
            }
        }
    }
```

**Comment by lisby** [comment]
The same issue is probably present on additional default entities - Contracts, Orders and invoices, and potentially more.
